# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39b39c9e606f8f5ffc9f5796c05da8545c7a9dac598b12ac83b167e081d0554763c3f04cdd512ccaecc6b7c3cc49f5029870d9aea1e2b1cd5ff8c120ee96d4d5

test:
  secret_key_base: d31c3657e88b64e6bf017cb2d2d744886547447faf0f3a757ffe36e326d77a54feaeefb6213b03141c48dd45c85656182721d36b1e232e6d2a8ca800a9ebe979

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
